{
 "title": "LDI",
 "time": { "from": "2026-07-20T23:00:00.000Z", "to": "2026-07-21T05:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "Factory",
    "query": "SELECT DISTINCT factory \nFROM ldi_data \nORDER BY factory;"
   },
   {
    "name": "process",
    "query": "SELECT DISTINCT process \nFROM ldi_data \nWHERE factory IN ($Factory) \nORDER BY process;"
   },
   {
    "name": "Eqp",
    "query": "SELECT DISTINCT eqp_id \nFROM ldi_data \nWHERE factory IN ($Factory) AND process IN ($process) \nORDER BY eqp_id;"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "_________________________________________________________"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  NOW() AS \"time\";"
    }
   ]
  },
  {
   "title": "Job Context (Current Production)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT mo AS \"mo\", \r\nfpn AS \"fpn\", \r\nlayer_name AS \"Layer\", \r\nresist_dosage AS \"Resist\" \r\nFROM ldi_data \r\nWHERE $__timeFilter(\"time\") AND eqp_id IN (${Eqp:singlequote}) \r\nORDER BY \"time\" \r\n"
    }
   ]
  },
  {
   "title": "Job Progress",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT (board_no * 100.0 / NULLIF(total_board, 0)) AS \"Progress (%)\", \r\nboard_no AS \"Current Board\", \r\ntotal_board AS \"Total Boards\" \r\nFROM ldi_data \r\nWHERE $__timeFilter(\"time\") AND eqp_id IN (${Eqp:singlequote}) \r\nORDER BY \"time\" \r\n"
    }
   ]
  },
  {
   "title": "Hourly Throughput (Max total_board)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  time_bucket('1h', \"time\")::timestamptz AS time,\r\n  COUNT(*) AS board\r\nFROM ldi_data\r\nWHERE $__timeFilter(\"time\") AND eqp_id IN (${Eqp:sqlstring})\r\nGROUP BY 1\r\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Process Quality Parameters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\nair_vacuum AS \"Air Vacuum\", \r\nscan_speed AS \"Scan Speed\", \r\nresist_dosage AS \"Resist Dosage\",\r\nthickness AS \"thickness\"\r\nFROM ldi_data \r\nWHERE $__timeFilter(\"time\") AND eqp_id IN (${Eqp:singlequote}) \r\nORDER BY \"time\" \r\n--DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Machine State Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT (\"time\")::timestamptz AS time,\r\neqp_id AS metric, \r\nCASE WHEN state=TRUE THEN 1 ELSE 0 END AS state \r\nFROM ldi_data WHERE $__timeFilter(\"time\") AND eqp_id = ${Eqp:sqlstring}\r\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Cycle Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT (\"time\")::timestamptz AS time,\n  eqp_id AS metric,\n  total_time AS \"Cycle Time\"\n--EXTRACT(EPOCH FROM (\"time\" - LAG(\"time\") OVER (ORDER BY \"time\"))) AS \"Actual Time Gap (s)\"\nFROM ldi_data\nWHERE $__timeFilter(\"time\") AND eqp_id IN (${Eqp:sqlstring})\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Temperature Trend (C)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT (\"time\")::timestamptz AS time,\r\n  eqp_id AS metric,\r\n  temperature AS \"temp\"\r\nFROM ldi_data\r\nWHERE $__timeFilter(\"time\") AND eqp_id IN (${Eqp:sqlstring})\r\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Recent Alarms Detail",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT logdate::timestamptz AS \"Time\", \r\nalarm_type AS \"Type\", \r\nalarm_msg AS \"Message\", \r\nalarm_detail AS \"Detail\" \r\nFROM v_ldi_alarm_detail \r\nWHERE $__timeFilter(logdate) AND eqp_id = ${Eqp:sqlstring} \r\nORDER BY logdate \r\nDESC LIMIT 100;"
    }
   ]
  },
  {
   "title": "Humidity Trend (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT (\"time\")::timestamptz AS time,\r\n  eqp_id AS metric,\r\n  humidity AS \"humidity\"\r\nFROM ldi_data\r\nWHERE $__timeFilter(\"time\") AND eqp_id IN (${Eqp:sqlstring})\r\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "PE (POSITION ERROR)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  (\"time\")::timestamptz AS \"time\",\r\n  pe_1, pe_2, pe_3, pe_4, pe_5, pe_6\r\nFROM ldi_data\r\nWHERE $__timeFilter(\"time\")\r\n  AND eqp_id IN (${Eqp:singlequote})\r\n  AND pe_1 IS NOT NULL\r\nORDER BY \"time\" DESC\r\nLIMIT 1;"
    },
    {}
   ]
  },
  {
   "title": "JE",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  (\"time\")::timestamptz AS \"time\",\r\n  je_1, je_2, je_3, je_4\r\nFROM ldi_data\r\nWHERE $__timeFilter(\"time\")\r\n  AND eqp_id IN (${Eqp:singlequote})\r\n  AND je_1 IS NOT NULL\r\nORDER BY \"time\" DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Scale Compensation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT \r\n(\"time\")::timestamptz AS \"time\",\r\nscale_x::NUMERIC(18, 6) AS \"Scale X\", \r\nscale_y::NUMERIC(18, 6) AS \"Scale Y\" \r\nFROM ldi_data \r\nWHERE $__timeFilter(\"time\") AND eqp_id IN (${Eqp:singlequote}) \r\nORDER BY \"time\" \r\n"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  (\"time\")::timestamptz AS \"time\",\r\n  pe_1, pe_2, pe_3, pe_4, pe_5, pe_6,\r\n  je_1, je_2, je_3, je_4\r\nFROM ldi_data\r\nWHERE $__timeFilter(\"time\")\r\n  AND eqp_id IN (${Eqp:singlequote})\r\nORDER BY \"time\" ASC;"
    }
   ]
  }
 ]
}