apiVersion: 1
deleteDatasources:
  - name: TimescaleDB
    orgId: 1
  - name: LDI
    orgId: 1
  - name: Prometheus
    orgId: 1
  - name: LDI-Main
    orgId: 1
  - name: ldi-postgres
    orgId: 1
datasources:
  - name: TimescaleDB
    uid: timescaledb
    type: postgres
    access: proxy
    url: ims-pgbouncer:5432
    database: ims
    user: ${GRAFANA_DB_USER}
    secureJsonData:
      password: ${GRAFANA_DB_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
      maxOpenConns: 20
      maxIdleConns: 5
      connMaxLifetime: 14400
  - name: LDI
    uid: LDI
    type: postgres
    access: proxy
    url: ims-timescaledb-2:5432
    isDefault: true
    database: ims
    user: ${GRAFANA_DB_USER}
    secureJsonData:
      password: ${GRAFANA_DB_PASSWORD}
    jsonData:
      database: ims
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
      maxOpenConns: 20
      maxIdleConns: 5
      connMaxLifetime: 14400
