apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: timescaledb
    type: postgres
    access: proxy
    url: ${POOLER_HOST}:${POOLER_PORT}
    database: ims
    user: ${POSTGRES_USER}
    secureJsonData:
      password: $__file{/run/secrets/postgres_password}
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
      maxOpenConns: 20
      maxIdleConns: 5
      connMaxLifetime: 14400
